spring.application.name=RetailStoreManagement_Team

# ==============================
# ENCODING
# ==============================
spring.thymeleaf.encoding=UTF-8

# ==============================
# SQL SERVER
# ==============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ==============================
# FIX DATA.SQL
# ==============================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.platform=sqlserver
# spring.sql.init.continue-on-error=true  <-- t?m comment ?? debug
#spring.application.name=RetailStoreManagement_Team
#
## ==============================
## ENCODING
## ==============================
#spring.thymeleaf.encoding=UTF-8
## ==============================
## SQL SERVER
## ==============================
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DA;encrypt=true;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=123
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.sql.init.platform=sqlserver
#
## ==============================
## JPA / HIBERNATE
## ==============================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## Giữ nguyên tên bảng
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
## SQL Server dialect
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.continue-on-error=true